# This workflow runs anytime new commits are added to master branch.
# It runs all network tests on the master branch using linux and one
# python version.
name: master_network_tests
on:
  push:
    branches:
      - master

jobs:
  network_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: test3.9
          use-mamba: true
          python-version: 3.9

      - uses: actions/cache@v2
        with:
          path: /usr/share/miniconda3/envs/test3.9
          key: ${{ matrix.label }}-conda-py3.9-${{ hashFiles('.github/test_conda_env-3.9.yml') }}-${{ steps.date.outputs.date }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run: mamba env update -n test3.9 -f .github/test_conda_env-3.9.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: install obspy
        shell: bash -l {0}
        run: |
          python -m pip install -e .[tests]

      - name: run test suite
        shell: bash -l {0}
        run: |
          obspy-runtests --network --cov obspy --cov-report='xml' --cov-append --report

      - name: upload coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: obspy/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
